### ISSUE TITLE
Form fields too small when viewport very wide

### ISSUE THREAD

**Issue by jonny-no1** [fourlabsldn/fl-interactive-form#7]
At a viewport of 2200px width, fields are only 300px wide.

![screen shot 2016-08-11 at 11 11 22](https://cloud.githubusercontent.com/assets/282458/17585546/5d8e4ffa-5fb4-11e6-8553-92b418d687c9.png)

**Comment by lazamar** [comment]
Fixed in commit [0e1e559](https://github.com/fourlabsldn/fl-interactive-form/commit/0e1e55905c6299f2bd5a21d71f3013bfcdbce5de)
